version: "3"

services:
  nginx-service:
    container_name: nginx
    build: ./docker/nginx/
    restart: always
    command: nginx -g "daemon off;"
    depends_on:
      - php-service
    links:
      - php-service
    ports:
      - 8000:80
    volumes:
      - ./www/:/var/www/html/
      - ./docker/nginx/log:/var/log/nginx/
    networks:
      - www

  php-service:
    container_name: php
    build: ./docker/php
    restart: always
    volumes:
      - ./www/:/var/www/html/
    ports:
      - 9000:9000
    networks:
      - www

  mysql-service:
    container_name: mysql
    build: ./docker/mysql
    restart: always
    volumes:
      - database:/var/lib/mysql/
    networks:
      - www
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - php-service

  phpmyadmin-service:
    container_name: phpmyadmin
    build: ./docker/phpmyadmin
    depends_on:
      - mysql-service
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql-service
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - www

networks:
  www:


volumes:
  database:
